
modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId="armadeus" #mandatory
version="0.0.1-1.19" #mandatory
displayName="Project : Armadeus" #mandatory
logoFile="armadeus.png" #optional

credits="Decimation <3" #optional

authors="G_ab, Hell" #optional


# The description text for the mod (multi line!) (#mandatory)
description='''
Nostagia Sad ;(
all love to Deci
RIP
o7 o7
'''

[[dependencies.armadeus]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[43,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.armadeus]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
